### ISSUE TITLE
Feature Request: Bounding Boxes

### ISSUE THREAD

**Issue by alistairheath** [Pantrist-dev/capacitor-plugin-ml-kit-text-recognition#2]
Hi everyone, just wanted to write a quick post saying thankyou! I've been looking for a way to do OCR in an Ionic app all weekend trying different methods of formatting images to improve accuracy for Tesseract and this got the problem right on the first try with no formatting.

I know the original ML Kit Model can return bounding boxes with each line and it would be great to see this feature added to the returned result. I'm a Javascript developer and happy to help if anyone can point me in the right direction!

**Comment by NLueg** [comment]
Hey @alistairheath! I'm really sorry for the late response. I actually received no notification for your issue ... Seems like I forgot to watch changes to this repository.
I actually need this feature too now, so I will add this soon.

**Comment by alistairheath** [comment]
Hi @NLueg, I've been experimenting with the code recently and now have a folk with bounding boxes and rectangles for elements. I need to upload it back to my GitHub folk but I can do that shortly. It's definitely an experiment because I've not used Swift, Kotlin or even GitHub properly before so will appreciate your feedback once I upload!

**Comment by NLueg** [comment]
Hey @alistairheath I actually just published the version `2.0.0` of the plugin. Now, almost every result of the ML-Kit gets returned by the plugin. Can you have a look into the new version?
If you want, I nevertheless can have a look at your changes.

**Comment by alistairheath** [comment]
Great minds think alike, I'll have a look at Version 2.0.0! Quite keen to help out more on the project, so let me know if I can help!

**Comment by NLueg** [comment]
Sure, thank you! I will close this issue, if you notice any problems you can of course reopen it.
