### ISSUE TITLE
Error en implementacion de 

### ISSUE THREAD

**Issue by ANDRESFCC** [Pantrist-dev/capacitor-plugin-ml-kit-text-recognition#5]
hello I have been trying to use it but when implementing in ionic capacitor, I have an error in the "DetectImageOptions" interface, how can I implement it if I already have the base64 image.

Thank you

**Comment by NLueg** [comment]
Hey @ANDRESFCC! If you have a base64 image, you should saved it as an `string`. Then you can just pass it into the `DetectImageOptions` like this:

```ts
const myBase64Image = '....';
const imageOptions: DetectImageOptions = {
  base64Image: myBase64Image
};
CapacitorPluginMlKitTextRecognition.detectText(imageOptions).then((result) => ...);
```

**Comment by NLueg** [comment]
Closed as there is no more progress.
